name: A workflow for my hello world file
on: workflow_dispatch
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
              echo "hello world"
              curl -H "Authorization: token ed922bb0af9dbf2ddb9b8ba6680287e321054d14" -H 'Accept: application/vnd.github.everest-preview+json' https://api.github.com/repos/rubikloud/auto-release-test/dispatches -d '{"event_type": "awesomeness", "client_payload": {"foo": "bar", "tag": "v1.1", "name": "Release v1.1"}}'
