name: A workflow for my hello world file
on: workflow_dispatch
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
              echo "hello world"
              git config --global user.name "Sagnik Som"
              git config --global user.email sagniksom99@gmail.com
              curl -H "Authorization: token 46882bf8c03e5d747c39a5bb4cd628e34d3ece75" -H 'Accept: application/vnd.github.everest-preview+json' https://api.github.com/repos/rubikloud/auto-release-test/dispatches -d '{"event_type": "Create Release", "client_payload": {"foo": "bar", "tag": "v2.5", "name": "my release"}}'
              
